#
# Integration Test Config: General
#

listenAddressSingleHTTPFrontend: 0.0.0.0:1337

logLevel: "DEBUG"
checkForUpdates: false

pageTitle: "My Custom App"

actions:
- title: sleep 2 seconds
  shell: sleep 2
  icon: "&#x1F971"
