#
# Integration Test Config: General
#

listenAddressSingleHTTPFrontend: 0.0.0.0:1337

showNavigation: false
checkForUpdates: false

# Actions (buttons) to show up on the WebUI:
actions:
- title: Ping example.com
  shell: ping example.com -c 1
  icon: ping
